ElementareTeilchen:
  Neos:
    ExternalRedirect:
      statusCode: 301

Neos:
  Neos:
    userInterface:
      translation:
        autoInclude:
          ElementareTeilchen.Neos.ExternalRedirect:
            - 'NodeTypes/*'
